name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or the branch you use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Asegúrate de usar la versión correcta de Flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Copy assets to build/web
        run: |
          mkdir -p build/web/assets/images
          cp -r assets/images/* build/web/assets/images/
          cp build/web/AssetManifest.json build/web/assets/
          cp build/web/FontManifest.json build/web/assets/
          cp build/web/NOTICES build/web/assets/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
